package pl.aplikacjemobilne.mykitchen.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color

val appColorScheme = ColorScheme(
    primary = Color(0xFFD4540A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFF5F0EB),
    onPrimaryContainer = Color(0xFF1C1A17),
    inversePrimary = Color(0xFFFFB68F),
    secondary = Color(0xFF8B5A3C),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFE0CC),
    onSecondaryContainer = Color(0xFF2D1810),
    tertiary = Color(0xFF6B8E5A),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD9EFCA),
    onTertiaryContainer = Color(0xFF1F2E14),
    background = Color(0xFFF5F0EB),
    onBackground = Color(0xFF1A1008),
    surface = Color(0xFFF5F0EB),
    onSurface = Color(0xFF1A1008),
    surfaceVariant = Color(0xFFEDE4DA),
    onSurfaceVariant = Color(0xFF5C4B3F),
    surfaceTint = Color(0xFFD4540A),
    inverseSurface = Color(0xFF1A1410),
    inverseOnSurface = Color(0xFFF5F0EB),
    error = Color(0xFFB3261E),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFF9DEDC),
    onErrorContainer = Color(0xFF410E0B),
    outline = Color(0xFFA89788),
    outlineVariant = Color(0xFFD8CCC0),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFAF5F0),
    surfaceContainer = Color(0xFFEFE7DD),
    surfaceContainerHigh = Color(0xFFE9E0D5),
    surfaceContainerHighest = Color(0xFFE3D9CC),
    surfaceContainerLow = Color(0xFFF2ECE3),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFDED5C9),
    primaryFixed = Color(0xFFFFDBC4),
    primaryFixedDim = Color(0xFFFFB68F),
    onPrimaryFixed = Color(0xFF3D1500),
    onPrimaryFixedVariant = Color(0xFF8B3A0F),
    secondaryFixed = Color(0xFFFFE0CC),
    secondaryFixedDim = Color(0xFFE8B89A),
    onSecondaryFixed = Color(0xFF2D1810),
    onSecondaryFixedVariant = Color(0xFF6B4528),
    tertiaryFixed = Color(0xFFD9EFCA),
    tertiaryFixedDim = Color(0xFFB8D3A6),
    onTertiaryFixed = Color(0xFF1F2E14),
    onTertiaryFixedVariant = Color(0xFF4F6E40),
)
